#!/usr/bin/env bash
# Axiom gate for the SATurday accepted tree.
#
# Acceptance bar (docs/p-vs-np-proof-standards.md):
#   1. lake build succeeds.
#   2. No sorry outside Frontier-marked files in the accepted tree.
#   3. Every declaration in scripts/accepted_declarations.txt depends only on the
#      three standard axioms: propext, Classical.choice, Quot.sound.
#
# Exit 0 on pass, 1 on any failure. Verbose by design: every check logs.

set -u
WORKSPACE="$(git rev-parse --show-toplevel)"
THEORY_DIR="$WORKSPACE/theory"
DECLS_FILE="$WORKSPACE/scripts/accepted_declarations.txt"
ALLOWED_AXIOMS="propext|Classical\.choice|Quot\.sound"
FAIL=0

echo "[axiom-gate] workspace: $WORKSPACE"

# ---------------------------------------------------------------- 1. build ---
echo "[axiom-gate] step 1: lake build"
cd "$THEORY_DIR" || { echo "[axiom-gate] FAIL: theory dir missing"; exit 1; }
if ! lake build 2>&1 | tail -5; then
  echo "[axiom-gate] FAIL: lake build failed"
  exit 1
fi
echo "[axiom-gate] build OK"

# ------------------------------------------------- 2. sorry quarantine scan ---
# Convention: work-in-progress files must contain a namespace marker 'Frontier'.
# Any sorry in a file without the marker fails the gate.
echo "[axiom-gate] step 2: sorry scan (Frontier quarantine)"
SORRY_FILES=$(rg -l "sorry" --glob "*.lean" Theory 2>/dev/null || true)
FRONTIER_COUNT=0
for f in $SORRY_FILES; do
  if rg -q "Frontier" "$f"; then
    N=$(rg -c "sorry" "$f")
    FRONTIER_COUNT=$((FRONTIER_COUNT + N))
    echo "[axiom-gate] quarantined frontier sorries: $f ($N)"
  else
    echo "[axiom-gate] FAIL: sorry outside Frontier namespace in $f"
    rg -n "sorry" "$f"
    FAIL=1
  fi
done
echo "[axiom-gate] accepted tree sorry violations: $FAIL (frontier sorries reported: $FRONTIER_COUNT)"

# ------------------------------------------------------- 3. axiom check -------
echo "[axiom-gate] step 3: axiom check for accepted declarations"
if [ ! -f "$DECLS_FILE" ]; then
  echo "[axiom-gate] FAIL: $DECLS_FILE missing"
  exit 1
fi

GATE_FILE="$THEORY_DIR/AxiomGateTmp.lean"
{
  echo "import Theory"
  echo "-- generated by scripts/check_axioms.sh; not part of the library"
  rg -v "^\s*(#|$)" "$DECLS_FILE" | while read -r decl; do
    echo "#print axioms $decl"
  done
} > "$GATE_FILE"

OUTPUT=$(lake env lean "$GATE_FILE" 2>&1)
STATUS=$?
rm -f "$GATE_FILE"

echo "$OUTPUT"
if [ $STATUS -ne 0 ]; then
  echo "[axiom-gate] FAIL: axiom probe file did not elaborate (bad declaration name?)"
  exit 1
fi

# Each line looks like: 'Foo.bar' depends on axioms: [propext, Classical.choice]
# or: 'Foo.bar' does not depend on any axioms
while IFS= read -r line; do
  case "$line" in
    *"depends on axioms"*)
      AXES=$(echo "$line" | sed -E 's/.*\[(.*)\].*/\1/')
      BAD=$(echo "$AXES" | tr ',' '\n' | sed 's/^ *//; s/ *$//' | rg -v "^($ALLOWED_AXIOMS)$" || true)
      if [ -n "$BAD" ]; then
        echo "[axiom-gate] FAIL: nonstandard axiom(s) [$BAD] in: $line"
        FAIL=1
      fi
      ;;
  esac
done <<< "$OUTPUT"

if [ $FAIL -eq 0 ]; then
  echo "[axiom-gate] PASS: build green, accepted tree sorry free, axioms within {propext, Classical.choice, Quot.sound}"
  exit 0
else
  echo "[axiom-gate] FAIL: see messages above"
  exit 1
fi
