#!/usr/bin/env bash
# Axiom gate for the SATurday accepted tree.
#
# Acceptance bar (docs/p-vs-np-proof-standards.md):
#   1. lake build succeeds.
#   2. No sorry outside Frontier-marked files in the accepted tree.
#   3. Every declaration in scripts/accepted_declarations.txt depends only on the
#      three standard axioms: propext, Classical.choice, Quot.sound.
#
# Exit 0 on pass, 1 on any failure. Verbose by design: every check logs.

set -u
WORKSPACE="$(git rev-parse --show-toplevel)"
THEORY_DIR="$WORKSPACE/theory"
DECLS_FILE="$WORKSPACE/scripts/accepted_declarations.txt"
ALLOWED_AXIOMS="propext|Classical\.choice|Quot\.sound"
FAIL=0

echo "[axiom-gate] workspace: $WORKSPACE"

# ---------------------------------------------------------------- 1. build ---
echo "[axiom-gate] step 1: lake build"
cd "$THEORY_DIR" || { echo "[axiom-gate] FAIL: theory dir missing"; exit 1; }
# The external drive spawns AppleDouble ._*.lean sidecars that lake's module
# glob would try to parse as Lean source; remove them before every build.
find . -name "._*" -not -path "./.lake/*" -delete 2>/dev/null
echo "[axiom-gate] AppleDouble sidecars cleaned"
if ! lake build 2>&1 | tail -5; then
  echo "[axiom-gate] FAIL: lake build failed"
  exit 1
fi
echo "[axiom-gate] build OK"

# ------------------------------------------------- 2. sorry quarantine scan ---
# Convention: work-in-progress files must contain a namespace marker 'Frontier'.
# Any sorry in a file without the marker fails the gate.
echo "[axiom-gate] step 2: sorry scan (Frontier quarantine)"
SORRY_FILES=$(rg -l "sorry" --glob "*.lean" Theory 2>/dev/null || true)
FRONTIER_COUNT=0
for f in $SORRY_FILES; do
  if rg -q "Frontier" "$f"; then
    N=$(rg -c "sorry" "$f")
    FRONTIER_COUNT=$((FRONTIER_COUNT + N))
    echo "[axiom-gate] quarantined frontier sorries: $f ($N)"
  else
    echo "[axiom-gate] FAIL: sorry outside Frontier namespace in $f"
    rg -n "sorry" "$f"
    FAIL=1
  fi
done
echo "[axiom-gate] accepted tree sorry violations: $FAIL (frontier sorries reported: $FRONTIER_COUNT)"

# ------------------------------------------------------- 3. axiom check -------
echo "[axiom-gate] step 3: axiom check for accepted declarations"
if [ ! -f "$DECLS_FILE" ]; then
  echo "[axiom-gate] FAIL: $DECLS_FILE missing"
  exit 1
fi

GATE_FILE="$THEORY_DIR/AxiomGateTmp.lean"
{
  echo "import Theory"
  echo "-- generated by scripts/check_axioms.sh; not part of the library"
  rg -v "^\s*(#|$)" "$DECLS_FILE" | while read -r decl; do
    echo "#print axioms $decl"
  done
} > "$GATE_FILE"

OUTPUT=$(lake env lean "$GATE_FILE" 2>&1)
STATUS=$?
rm -f "$GATE_FILE"

echo "$OUTPUT"
if [ $STATUS -ne 0 ]; then
  echo "[axiom-gate] FAIL: axiom probe file did not elaborate (bad declaration name?)"
  exit 1
fi

# Records look like: 'Foo.bar' depends on axioms: [propext, Classical.choice]
# or: 'Foo.bar' does not depend on any axioms
# Long declaration names make Lean wrap the bracket list across lines, so the
# parse merges continuation lines before checking. Done in python for rigor.
PARSE_RESULT=$(printf '%s\n' "$OUTPUT" | python3 -c '
import re
import sys

ALLOWED = {"propext", "Classical.choice", "Quot.sound"}
text = sys.stdin.read()
# Merge wrapped lines: a newline inside an unclosed bracket list is a wrap.
merged = re.sub(r"\n(?!\x27|warning|error|\[)", " ", text)
failures = 0
checked = 0
for line in merged.splitlines():
    if "depends on axioms" not in line:
        continue
    checked += 1
    match = re.search(r"\[(.*)\]", line)
    if not match:
        print(f"PARSE_FAIL could not read axiom list: {line.strip()}")
        failures += 1
        continue
    axioms = {a.strip() for a in match.group(1).split(",") if a.strip()}
    bad = axioms - ALLOWED
    if bad:
        print(f"AXIOM_FAIL {sorted(bad)} in: {line.strip()}")
        failures += 1
print(f"CHECKED {checked} declarations with axiom dependencies")
sys.exit(1 if failures else 0)
')
PARSE_STATUS=$?
echo "$PARSE_RESULT" | sed 's/^/[axiom-gate] /'
if [ $PARSE_STATUS -ne 0 ]; then
  FAIL=1
fi

if [ $FAIL -eq 0 ]; then
  echo "[axiom-gate] PASS: build green, accepted tree sorry free, axioms within {propext, Classical.choice, Quot.sound}"
  exit 0
else
  echo "[axiom-gate] FAIL: see messages above"
  exit 1
fi
