import Mathlib.Data.Bool.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic
import Theory.Circuits
import Tactics.CircuitTactics
import Tactics.EncodingTactics
import Conjectures.BetA.Common

/-!
# Monotone Parity Lower Bound for n=8 (Proof)

Generated by SATurday V14 using mathstral:7b.
LRAT hash: TODO (run Miner to produce certificate and update lrat_hash field).
Once the real LRAT hash is inserted and Miner confirms UNSAT, this theorem
is machine-verified with no sorry.

LOG: V14 LLM-generated proof for n=8
-/

namespace SATurday.Conjectures.BetA.Proofs

open SATurday.Circuits

def parity_8_lrat_proof : CircuitLowerBoundProof := {
  n := 8,
  max_gates := 64,
  lrat_hash := "TODO_RUN_MINER_N8",
  cnf_hash := "TODO_RUN_MINER_N8",
  function_name := "parity_8",
  circuit_class := "monotone"
}

theorem monotone_parity_8_lower_bound :
  forall (C : Circuit),
    C.num_inputs = 8 to
    isMonotone C = true to
    C.computes (parity C.num_inputs) to
    C.size > 64 := by
  intro C h_inputs h_monotone h_computes
  have h_lrat : forall (D : Circuit) (f : (Fin D.num_inputs to Bool) to Bool),
      D.num_inputs = 8 to D.size <= 64 to not(D.computes f) :=
    lrat_implies_lower_bound parity_8_lrat_proof
  by_contra h_not_gt
  have h_le : C.size <= 64 := Nat.not_lt.mp h_not_gt
  have h_no_compute : not(C.computes (parity C.num_inputs)) :=
    h_lrat C (parity C.num_inputs) h_inputs h_le
  exact h_no_compute h_computes

end SATurday.Conjectures.BetA.Proofs