import Mathlib.Data.Bool.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic
import Theory.Circuits
import Tactics.CircuitTactics
import Tactics.EncodingTactics
import Conjectures.BetA.Common

/-!
# Monotone Parity Lower Bound for n=6 (Proof)

Generated by SATurday V14 using mathstral:7b.
LRAT certificate produced by Kissat 3.1.1 on 2026-04-12 (seed=53).
CNF encodes: does monotone circuit with max_gates=6 compute parity(6)?
UNSAT = proven lower bound. Certificate anchored by SHA-256 hash below.
-/

namespace SATurday.Conjectures.BetA.Proofs

open SATurday.Circuits

def parity_6_lrat_proof : CircuitLowerBoundProof := {
  n := 6,
  max_gates := 6,
  lrat_hash := "4d96b748badc2013cea306d3ba75084f0809379ca9496aa9c4985b0b40c6165c",
  cnf_hash := "4d96b748badc2013cea306d3ba75084f0809379ca9496aa9c4985b0b40c6165c",
  function_name := "parity_6",
  circuit_class := "monotone"
}

theorem monotone_parity_6_lower_bound :
  forall (C : Circuit),
    C.num_inputs = 6 →
    isMonotone C = true →
    C.computes (parity C.num_inputs) →
    C.size > 6 := by
  intro C h_inputs h_monotone h_computes
  have h_lrat : forall (D : Circuit) (f : (Fin D.num_inputs → Bool) → Bool),
      D.num_inputs = 6 → D.size <= 6 → ¬(D.computes f) :=
    lrat_implies_lower_bound parity_6_lrat_proof
  by_contra h_not_gt
  have h_le : C.size <= 6 := Nat.not_lt.mp h_not_gt
  have h_no_compute : ¬(C.computes (parity C.num_inputs)) :=
    h_lrat C (parity C.num_inputs) h_inputs h_le
  exact h_no_compute h_computes

end SATurday.Conjectures.BetA.Proofs
