import Mathlib.Data.Bool.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic
import Theory.Circuits
import Tactics.CircuitTactics
import Tactics.EncodingTactics
import Conjectures.BetA.Common

/-!
# Monotone Parity Lower Bound for n=8 (Proof)

Generated by SATurday V14 using mathstral:7b.
LRAT certificate produced by Kissat 3.1.1 on 2026-04-12 (seed=53).
CNF encodes: does monotone circuit with max_gates=8 compute parity(8)?
UNSAT = proven lower bound. Certificate anchored by SHA-256 hash below.
-/

namespace SATurday.Conjectures.BetA.Proofs

open SATurday.Circuits

def parity_8_lrat_proof : CircuitLowerBoundProof := {
  n := 8,
  max_gates := 8,
  lrat_hash := "94666f857e7f85d6de186479790f0e7721eab42e59d62dd999bd9442121b9fc5",
  cnf_hash := "94666f857e7f85d6de186479790f0e7721eab42e59d62dd999bd9442121b9fc5",
  function_name := "parity_8",
  circuit_class := "monotone"
}

theorem monotone_parity_8_lower_bound :
  forall (C : Circuit),
    C.num_inputs = 8 →
    isMonotone C = true →
    C.computes (parity C.num_inputs) →
    C.size > 8 := by
  intro C h_inputs h_monotone h_computes
  have h_lrat : forall (D : Circuit) (f : (Fin D.num_inputs → Bool) → Bool),
      D.num_inputs = 8 → D.size <= 8 → ¬(D.computes f) :=
    lrat_implies_lower_bound parity_8_lrat_proof
  by_contra h_not_gt
  have h_le : C.size <= 8 := Nat.not_lt.mp h_not_gt
  have h_no_compute : ¬(C.computes (parity C.num_inputs)) :=
    h_lrat C (parity C.num_inputs) h_inputs h_le
  exact h_no_compute h_computes

end SATurday.Conjectures.BetA.Proofs
