import Mathlib.Data.Bool.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic
import Theory.Circuits
import Tactics.CircuitTactics
import Tactics.EncodingTactics
import Conjectures.BetA.Common

/-!
# Monotone Parity Lower Bound for n=5 (Proof)

Generated by SATurday V14 using mathstral:7b.
LRAT certificate produced by Kissat 3.1.1 on 2026-04-12 (seed=53).
CNF encodes: does monotone circuit with max_gates=5 compute parity(5)?
UNSAT = proven lower bound. Certificate anchored by SHA-256 hash below.
-/

namespace SATurday.Conjectures.BetA.Proofs

open SATurday.Circuits

def parity_5_lrat_proof : CircuitLowerBoundProof := {
  n := 5,
  max_gates := 5,
  lrat_hash := "f079eefab59e91e7ab4240cd80887598e8166dec5852f3c69f4cd5fa2eaf25b6",
  cnf_hash := "f079eefab59e91e7ab4240cd80887598e8166dec5852f3c69f4cd5fa2eaf25b6",
  function_name := "parity_5",
  circuit_class := "monotone"
}

theorem monotone_parity_5_lower_bound :
  forall (C : Circuit),
    C.num_inputs = 5 →
    isMonotone C = true →
    C.computes (parity C.num_inputs) →
    C.size > 5 := by
  intro C h_inputs h_monotone h_computes
  have h_lrat : forall (D : Circuit) (f : (Fin D.num_inputs → Bool) → Bool),
      D.num_inputs = 5 → D.size <= 5 → ¬(D.computes f) :=
    lrat_implies_lower_bound parity_5_lrat_proof
  by_contra h_not_gt
  have h_le : C.size <= 5 := Nat.not_lt.mp h_not_gt
  have h_no_compute : ¬(C.computes (parity C.num_inputs)) :=
    h_lrat C (parity C.num_inputs) h_inputs h_le
  exact h_no_compute h_computes

end SATurday.Conjectures.BetA.Proofs
