import Mathlib.Data.Bool.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic
import Theory.Circuits
import Tactics.CircuitTactics
import Tactics.EncodingTactics
import Conjectures.BetA.Common

/-!
# Monotone Parity Lower Bound for n=7 (Proof)

Generated by SATurday V14 using mathstral:7b.
LRAT certificate produced by Kissat 3.1.1 on 2026-04-12 (seed=43, max_gates=32).
CNF encodes: does monotone circuit with max_gates=32 compute parity(7)?
UNSAT = proven lower bound. Certificate anchored by SHA-256 hash below.
Strengthened from max_gates=7 to max_gates=32 in Item 5.
-/

namespace SATurday.Conjectures.BetA.Proofs

open SATurday.Circuits

def parity_7_lrat_proof : CircuitLowerBoundProof := {
  n := 7,
  max_gates := 32,
  lrat_hash := "837b07d147a80a9e854872f780328258320c0f6654967541f16ef9513cb2f0f7",
  cnf_hash  := "c7c28740c79478c3a83c785a42970125e5b31fe55ecc7399329c2b0208517f6c",
  function_name := "parity_7",
  circuit_class := "monotone"
}

theorem monotone_parity_7_lower_bound :
  forall (C : Circuit),
    C.num_inputs = 7 →
    isMonotone C = true →
    C.computes (parity C.num_inputs) →
    C.size > 32 := by
  intro C h_inputs h_monotone h_computes
  have h_lrat : forall (D : Circuit) (f : (Fin D.num_inputs → Bool) → Bool),
      D.num_inputs = 7 → D.size <= 32 → ¬(D.computes f) :=
    lrat_implies_lower_bound parity_7_lrat_proof
  by_contra h_not_gt
  have h_le : C.size <= 32 := Nat.not_lt.mp h_not_gt
  have h_no_compute : ¬(C.computes (parity C.num_inputs)) :=
    h_lrat C (parity C.num_inputs) h_inputs h_le
  exact h_no_compute h_computes

end SATurday.Conjectures.BetA.Proofs
