import Mathlib.Data.Bool.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Tactic
import Theory.Circuits
import Tactics.CircuitTactics
import Tactics.EncodingTactics
import Conjectures.BetA.Common

/-!
# Monotone Parity Lower Bound for n=5 (Proof)

Generated by SATurday V14 using mathstral:7b.
LRAT certificate produced by Kissat 3.1.1 on 2026-04-12 (seed=43, max_gates=32).
CNF encodes: does monotone circuit with max_gates=32 compute parity(5)?
UNSAT = proven lower bound. Certificate anchored by SHA-256 hash below.
Strengthened from max_gates=5 to max_gates=32 in Item 5.
-/

namespace SATurday.Conjectures.BetA.Proofs

open SATurday.Circuits

def parity_5_lrat_proof : CircuitLowerBoundProof := {
  n := 5,
  max_gates := 32,
  lrat_hash := "65c7c08bfa1d397bed84e6aabfb6f7426f12f818d37e61702f5694db8fe77bff",
  cnf_hash  := "9870c87589a938439d6aa22977f45da4fb6f9103a80be17ea4b46996f140bfb9",
  function_name := "parity_5",
  circuit_class := "monotone"
}

theorem monotone_parity_5_lower_bound :
  forall (C : Circuit),
    C.num_inputs = 5 →
    isMonotone C = true →
    C.computes (parity C.num_inputs) →
    C.size > 32 := by
  intro C h_inputs h_monotone h_computes
  have h_lrat : forall (D : Circuit) (f : (Fin D.num_inputs → Bool) → Bool),
      D.num_inputs = 5 → D.size <= 32 → ¬(D.computes f) :=
    lrat_implies_lower_bound parity_5_lrat_proof
  by_contra h_not_gt
  have h_le : C.size <= 32 := Nat.not_lt.mp h_not_gt
  have h_no_compute : ¬(C.computes (parity C.num_inputs)) :=
    h_lrat C (parity C.num_inputs) h_inputs h_le
  exact h_no_compute h_computes

end SATurday.Conjectures.BetA.Proofs
